name: Schedule Workflow importer Update

on:
  issues:
    type: open
  # schedule:
  #  - cron: '0 */24 * * *'  # At minute 0 past every 12th hour.

jobs:
  update-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Script
        run: python .github/workflows/workflowimporter.py
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_ASSISTER_PAT }}
          GITHUB_ORG: 'GuineaBot3Labs'
